volumes:
  lf8Starter_postgres_data:
    driver: local

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: hitec-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 9090
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
    ports:
      - "9090:9090"
    command:
      - start-dev
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/localhost/9090 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s

  postgres-employee:
    container_name: lf8Starter_postgres
    image: postgres:16.4
    volumes:
      - lf8Starter_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lf8Starter
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"